# Generated by Django 5.2.17 on 2026-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='restaurant_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
